### ISSUE TITLE
Write CSS mobile first

### ISSUE THREAD

**Issue by unrevised6419** [BraduCristina/One-Page-Website#4]
Write your css mobile first. ex:
Instead of this
```css
.portfolio {
  padding: 80px 0 80px;
}

@media (max-width: 768px) {
  .portfolio {
    padding: 30px;
  }
}
```
write this
```css
.portfolio {
  padding: 30px;
}

@media (min-width: 768px) {
  .portfolio {
     padding: 80px 0 80px;
  }
}
```

Use `max-width` as less as you can
